name: Build Windows Executable

on:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build Windows executable
      run: |
        python -m pip install pyinstaller
        pyinstaller --onefile --add-data "AzerothAuctionAssassinData:AzerothAuctionAssassinData" --add-data "utils:utils" AzerothAuctionAssassin.py

    - name: Save Windows executable as artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-executable
        path: dist\AzerothAuctionAssassin.exe